const actions = {
  HOME: {
    GETHOME: 'GETHOME',
    LOADHOME: 'LOADHOME',
  },
  CALCULATOR: {
    LOAD_CALCULATOR_DATA: 'LOAD_CALCULATOR_DATA',
    LOAD_DATA: 'LOAD_DATA',
    UNLOAD_CALCULATOR_DATA: 'UNLOAD_CALCULATOR_DATA',
    CHANGE_FIELD_VALUE: 'CHANGE_FIELD_VALUE',
    SHOW_NEXT_STEP: 'SHOW_NEXT_STEP',
    SHOW_PREVIOUS_STEP: 'SHOW_PREVIOUS_STEP',
  },
};
export default actions;
